// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:crypto_app/features/home/data/models/coin_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CoinModelAdapter());
    registerAdapter(SparklineDataAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CoinModelAdapter());
    registerAdapter(SparklineDataAdapter());
  }
}
